FROM nginx:stable-alpine AS deploy
COPY nginx.conf /etc/nginx/conf.d/default.conf

FROM node:16 AS build
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .
RUN npx ng build

FROM deploy
COPY --from=build /usr/src/app/dist /usr/share/nginx/html